##Importing libraries

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu113


###Creating tensors

In [2]:
#Pytorch tensors are created using torch.Tensor()
scalar = torch.tensor(7)
scalar
#scalar.ndim

tensor(7)

In [3]:
#Getting tensor back as Puthon int 
scalar.item()

7

In [4]:
#Vectors
vector = torch.tensor([8,8])
vector

tensor([8, 8])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
#Matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
MATRIX[1]

tensor([ 9, 10])

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [11]:
TENSOR.ndim

3

In [12]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

##Random Tensors

###Start with random numbers -> look at data 
###-> update random numbers -> look at data 
###-> update random numbers

#####Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [14]:
# Create a random tensor of size (5, 6)
random_tensor = torch.rand(5, 6)
random_tensor

tensor([[0.3327, 0.2543, 0.8121, 0.5512, 0.6641, 0.2419],
        [0.1039, 0.6920, 0.7860, 0.2306, 0.3199, 0.1525],
        [0.6248, 0.9340, 0.8043, 0.9555, 0.9077, 0.8914],
        [0.6758, 0.8265, 0.0139, 0.5727, 0.7128, 0.9184],
        [0.6710, 0.2924, 0.1837, 0.1730, 0.7649, 0.5252]])

In [15]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(4, 224, 224)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([4, 224, 224]), 3)

Zeores and Ones


In [16]:
# A tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
# A tensor of all ones
ones = torch.ones(size=(3, 4)) 
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
ones.dtype

torch.float32

In [19]:
random_tensor.dtype

torch.float32

###A range of tensors and tensors-like

In [20]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##Tensor datatypes


1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device



In [22]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               # what datatype is the tensor (e.g. float32 or float16)
                               dtype=None, 
                               # What device is your tensor on
                               device=None, 
                               # whether or not to track gradients with this tensors operations
                               requires_grad=False) 
float_32_tensor

tensor([3., 6., 9.])

In [23]:
float_32_tensor.dtype

torch.float32

In [24]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [26]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [27]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

###Tensor attributes

> Tensors not right datatype 
- to do get datatype from a tensor, can use tensor.dtype

> Tensors not right shape 
- to get shape from a tensor, can use tensor.shape

> Tensors not on the right device 
- to get device from a tensor, can use tensor.device






In [28]:
#Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3514, 0.8194, 0.2648, 0.7713],
        [0.0266, 0.8353, 0.3811, 0.7840],
        [0.4679, 0.3890, 0.6890, 0.3994]])

In [29]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3514, 0.8194, 0.2648, 0.7713],
        [0.0266, 0.8353, 0.3811, 0.7840],
        [0.4679, 0.3890, 0.6890, 0.3994]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


###Tensor operations
Tensor opertions include:

Addition

Subtraction 

Multiplication (element-wise)

Division

Matrix multiplication

In [30]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 20

tensor([21, 22, 23])

In [31]:
# Multiply tensor by 10
tensor * 15

tensor([15, 30, 45])

In [32]:
# Substract 10
tensor - 45

tensor([-44, -43, -42])

In [33]:
#  PyTorch in-built functions to multiply 
torch.mul(tensor, 15)

tensor([15, 30, 45])

In [34]:
#  PyTorch in-built functions to add
torch.add(tensor, 20)

tensor([21, 22, 23])

In [35]:
# divide 
t1= torch.tensor([4, 16, 32])
torch.div(t1, 4)

###another way to perform division 

##1
#t= torch.tensor([4, 4, 4])
#torch.div(t1, t)

##2
#t= torch.tensor([4])
#torch.div(t1, t)

tensor([1., 4., 8.])

###Matrix multiplication

In [36]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [37]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [38]:
tensor

tensor([1, 2, 3])

In [39]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14