##Importing libraries

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu113


###Creating tensors

In [2]:
#Pytorch tensors are created using torch.Tensor()
scalar = torch.tensor(7)
scalar
#scalar.ndim

tensor(7)

In [3]:
#Getting tensor back as Puthon int 
scalar.item()

7

In [4]:
#Vectors
vector = torch.tensor([8,8])
vector

tensor([8, 8])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
#Matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
MATRIX[1]

tensor([ 9, 10])

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [11]:
TENSOR.ndim

3

In [12]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

##Random Tensors

###Start with random numbers -> look at data 
###-> update random numbers -> look at data 
###-> update random numbers

#####Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [14]:
# Create a random tensor of size (5, 6)
random_tensor = torch.rand(5, 6)
random_tensor

tensor([[0.9176, 0.0333, 0.9265, 0.1829, 0.3699, 0.5248],
        [0.0445, 0.2993, 0.0248, 0.5064, 0.4597, 0.2683],
        [0.9112, 0.7521, 0.8058, 0.7650, 0.5070, 0.0819],
        [0.0087, 0.3039, 0.3469, 0.8839, 0.8648, 0.9327],
        [0.8713, 0.8333, 0.4075, 0.6950, 0.2642, 0.9259]])

In [15]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(4, 224, 224)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([4, 224, 224]), 3)

Zeores and Ones


In [16]:
# A tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
# A tensor of all ones
ones = torch.ones(size=(3, 4)) 
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
ones.dtype

torch.float32

In [19]:
random_tensor.dtype

torch.float32

###A range of tensors and tensors-like

In [20]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##Tensor datatypes


1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device



In [22]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               # what datatype is the tensor (e.g. float32 or float16)
                               dtype=None, 
                               # What device is your tensor on
                               device=None, 
                               # whether or not to track gradients with this tensors operations
                               requires_grad=False) 
float_32_tensor

tensor([3., 6., 9.])

In [23]:
float_32_tensor.dtype

torch.float32

In [24]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [26]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [27]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

###Tensor attributes

> Tensors not right datatype 
- to do get datatype from a tensor, can use tensor.dtype

> Tensors not right shape 
- to get shape from a tensor, can use tensor.shape

> Tensors not on the right device 
- to get device from a tensor, can use tensor.device






In [28]:
#Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9795, 0.0641, 0.6693, 0.7340],
        [0.1558, 0.5252, 0.4374, 0.9071],
        [0.7537, 0.8644, 0.5453, 0.9500]])

In [29]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9795, 0.0641, 0.6693, 0.7340],
        [0.1558, 0.5252, 0.4374, 0.9071],
        [0.7537, 0.8644, 0.5453, 0.9500]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


###Tensor operations
Tensor opertions include:

Addition

Subtraction 

Multiplication (element-wise)

Division

Matrix multiplication

In [30]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 20

tensor([21, 22, 23])

In [31]:
# Multiply tensor by 10
tensor * 15

tensor([15, 30, 45])

In [32]:
# Substract 10
tensor - 45

tensor([-44, -43, -42])

In [33]:
#  PyTorch in-built functions to multiply 
torch.mul(tensor, 15)

tensor([15, 30, 45])

In [34]:
#  PyTorch in-built functions to add
torch.add(tensor, 20)

tensor([21, 22, 23])

In [35]:
# divide 
t1= torch.tensor([4, 16, 32])
torch.div(t1, 4)

###another way to perform division 

##1
#t= torch.tensor([4, 4, 4])
#torch.div(t1, t)

##2
#t= torch.tensor([4])
#torch.div(t1, t)

tensor([1., 4., 8.])

###Matrix multiplication

Ways of Mutiplicating 

1.Element-wise multiplication

2.Matrix mutliplication (dot product)

In [36]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [37]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [38]:
tensor

tensor([1, 2, 3])

In [39]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [40]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 5.1 ms, sys: 0 ns, total: 5.1 ms
Wall time: 7.07 ms


In [41]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 76 µs, sys: 0 ns, total: 76 µs
Wall time: 81.3 µs


tensor(14)

Matrix multiplication with appropriate shape 

In [42]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

#Both are 3*2 , 3*2 can not do matrix multiplication
#so we transpose so it becomes 3*2 and 2*3
#Transpose 
#A transpose switches the axes or dimensions of a given tensor.
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [43]:
#check the shape
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [44]:
#inner dimension must match 
print(f"Original shapes: \n tensor_A = {tensor_A.shape}, \n tensor_B = {tensor_B.shape}\n")
print(f"New shapes: \n tensor_A = {tensor_A.shape} (same shape as above),\n tensor_B.T = {tensor_B.T.shape} \n")
print(f"Multiplying:with same inner dimension \n {tensor_A.shape} @ {tensor_B.T.shape}")

Original shapes: 
 tensor_A = torch.Size([3, 2]), 
 tensor_B = torch.Size([3, 2])

New shapes: 
 tensor_A = torch.Size([3, 2]) (same shape as above),
 tensor_B.T = torch.Size([2, 3]) 

Multiplying:with same inner dimension 
 torch.Size([3, 2]) @ torch.Size([2, 3])


In [45]:
#Matrix Multipllication 
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

###Tensor Aggregation
Finidng min, max, mean, sum 

In [46]:
# Create a tensor
x = torch.arange(1, 200, 10)
x, x.dtype

(tensor([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121, 131,
         141, 151, 161, 171, 181, 191]), torch.int64)

In [47]:
#  min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [48]:
# max
torch.max(x), x.max()

(tensor(191), tensor(191))

In [49]:
#mean 
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

#note: the torch.mean() function requires a tensor of float32 datatype to work

(tensor(96.), tensor(96.))

In [50]:
# Find the sum
torch.sum(x), x.sum()

(tensor(1920), tensor(1920))

###Positional min and max

In [51]:
x

tensor([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121, 131,
        141, 151, 161, 171, 181, 191])

In [52]:
# Find the position in tensor that has the minimum value with argmin() 
#-> returns index position of targt tensor where the minimum value occurs 
x.argmin()

tensor(0)

In [53]:
x[0]

tensor(1)

In [54]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(19)

In [55]:
x[8]

tensor(81)