##Importing libraries

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu113


###Creating tensors

In [2]:
#Pytorch tensors are created using torch.Tensor()
scalar = torch.tensor(7)
scalar
#scalar.ndim

tensor(7)

In [3]:
#Getting tensor back as Puthon int 
scalar.item()

7

In [4]:
#Vectors
vector = torch.tensor([8,8])
vector

tensor([8, 8])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
#Matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
MATRIX[1]

tensor([ 9, 10])

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [11]:
TENSOR.ndim

3

In [12]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

##Random Tensors

###Start with random numbers -> look at data 
###-> update random numbers -> look at data 
###-> update random numbers

#####Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [14]:
# Create a random tensor of size (5, 6)
random_tensor = torch.rand(5, 6)
random_tensor

tensor([[0.9945, 0.4053, 0.9523, 0.0464, 0.7246, 0.5470],
        [0.8132, 0.3707, 0.2371, 0.7744, 0.1446, 0.4062],
        [0.8967, 0.1792, 0.2252, 0.6429, 0.0810, 0.3700],
        [0.2226, 0.9115, 0.2381, 0.6556, 0.7974, 0.8424],
        [0.9310, 0.2764, 0.7019, 0.9251, 0.7007, 0.5933]])

In [15]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(4, 224, 224)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([4, 224, 224]), 3)

Zeores and Ones


In [16]:
# A tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
# A tensor of all ones
ones = torch.ones(size=(3, 4)) 
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
ones.dtype

torch.float32

In [19]:
random_tensor.dtype

torch.float32

###A range of tensors and tensors-like

In [20]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##Tensor datatypes


1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device



In [22]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               # what datatype is the tensor (e.g. float32 or float16)
                               dtype=None, 
                               # What device is your tensor on
                               device=None, 
                               # whether or not to track gradients with this tensors operations
                               requires_grad=False) 
float_32_tensor

tensor([3., 6., 9.])

In [23]:
float_32_tensor.dtype

torch.float32

In [24]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [26]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [27]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])