##Importing libraries

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu113


###Creating tensors

In [2]:
#Pytorch tensors are created using torch.Tensor()
scalar = torch.tensor(7)
scalar
#scalar.ndim

tensor(7)

In [3]:
#Getting tensor back as Puthon int 
scalar.item()

7

In [4]:
#Vectors
vector = torch.tensor([8,8])
vector

tensor([8, 8])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
#Matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
MATRIX[1]

tensor([ 9, 10])

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [11]:
TENSOR.ndim

3

In [12]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

##Random Tensors

###Start with random numbers -> look at data 
###-> update random numbers -> look at data 
###-> update random numbers

#####Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [14]:
# Create a random tensor of size (5, 6)
random_tensor = torch.rand(5, 6)
random_tensor

tensor([[0.9762, 0.8116, 0.0175, 0.3907, 0.9896, 0.4286],
        [0.7098, 0.7265, 0.1168, 0.5143, 0.5054, 0.8220],
        [0.3866, 0.4876, 0.8454, 0.9203, 0.9134, 0.7027],
        [0.7627, 0.3600, 0.7786, 0.7609, 0.5535, 0.5063],
        [0.4792, 0.5459, 0.3944, 0.8811, 0.3074, 0.7507]])

In [15]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(4, 224, 224)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([4, 224, 224]), 3)

Zeores and Ones


In [16]:
# A tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
# A tensor of all ones
ones = torch.ones(size=(3, 4)) 
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
ones.dtype

torch.float32

In [19]:
random_tensor.dtype

torch.float32

###A range of tensors and tensors-like

In [20]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##Tensor datatypes


1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device



In [22]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               # what datatype is the tensor (e.g. float32 or float16)
                               dtype=None, 
                               # What device is your tensor on
                               device=None, 
                               # whether or not to track gradients with this tensors operations
                               requires_grad=False) 
float_32_tensor

tensor([3., 6., 9.])

In [23]:
float_32_tensor.dtype

torch.float32

In [24]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [26]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [27]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

###Tensor attributes

> Tensors not right datatype 
- to do get datatype from a tensor, can use tensor.dtype

> Tensors not right shape 
- to get shape from a tensor, can use tensor.shape

> Tensors not on the right device 
- to get device from a tensor, can use tensor.device






In [28]:
#Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.8454, 0.7866, 0.0014, 0.5212],
        [0.5575, 0.4316, 0.3466, 0.1046],
        [0.7097, 0.4461, 0.0835, 0.9958]])

In [29]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.8454, 0.7866, 0.0014, 0.5212],
        [0.5575, 0.4316, 0.3466, 0.1046],
        [0.7097, 0.4461, 0.0835, 0.9958]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


###Tensor operations
Tensor opertions include:

Addition

Subtraction 

Multiplication (element-wise)

Division

Matrix multiplication

In [30]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 20

tensor([21, 22, 23])

In [31]:
# Multiply tensor by 10
tensor * 15

tensor([15, 30, 45])

In [32]:
# Substract 10
tensor - 45

tensor([-44, -43, -42])

In [33]:
#  PyTorch in-built functions to multiply 
torch.mul(tensor, 15)

tensor([15, 30, 45])

In [34]:
#  PyTorch in-built functions to add
torch.add(tensor, 20)

tensor([21, 22, 23])

In [35]:
# divide 
t1= torch.tensor([4, 16, 32])
torch.div(t1, 4)

###another way to perform division 

##1
#t= torch.tensor([4, 4, 4])
#torch.div(t1, t)

##2
#t= torch.tensor([4])
#torch.div(t1, t)

tensor([1., 4., 8.])

###Matrix multiplication

Ways of Mutiplicating 

1.Element-wise multiplication

2.Matrix mutliplication (dot product)

In [36]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [37]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [38]:
tensor

tensor([1, 2, 3])

In [39]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [40]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 5.01 ms, sys: 0 ns, total: 5.01 ms
Wall time: 6.52 ms


In [41]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 55 µs, sys: 10 µs, total: 65 µs
Wall time: 69.6 µs


tensor(14)

Matrix multiplication with appropriate shape 

In [42]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

#Both are 3*2 , 3*2 can not do matrix multiplication
#so we transpose so it becomes 3*2 and 2*3
#Transpose 
#A transpose switches the axes or dimensions of a given tensor.
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [43]:
#check the shape
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [44]:
#inner dimension must match 
print(f"Original shapes: \n tensor_A = {tensor_A.shape}, \n tensor_B = {tensor_B.shape}\n")
print(f"New shapes: \n tensor_A = {tensor_A.shape} (same shape as above),\n tensor_B.T = {tensor_B.T.shape} \n")
print(f"Multiplying:with same inner dimension \n {tensor_A.shape} @ {tensor_B.T.shape}")

Original shapes: 
 tensor_A = torch.Size([3, 2]), 
 tensor_B = torch.Size([3, 2])

New shapes: 
 tensor_A = torch.Size([3, 2]) (same shape as above),
 tensor_B.T = torch.Size([2, 3]) 

Multiplying:with same inner dimension 
 torch.Size([3, 2]) @ torch.Size([2, 3])


In [45]:
#Matrix Multipllication 
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

###Tensor Aggregation
Finidng min, max, mean, sum 

In [46]:
# Create a tensor
x = torch.arange(1, 200, 10)
x, x.dtype

(tensor([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121, 131,
         141, 151, 161, 171, 181, 191]), torch.int64)

In [47]:
#  min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [48]:
# max
torch.max(x), x.max()

(tensor(191), tensor(191))

In [49]:
#mean 
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

#note: the torch.mean() function requires a tensor of float32 datatype to work

(tensor(96.), tensor(96.))

In [50]:
# Find the sum
torch.sum(x), x.sum()

(tensor(1920), tensor(1920))

###Positional min and max

In [51]:
x

tensor([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121, 131,
        141, 151, 161, 171, 181, 191])

In [52]:
# Find the position in tensor that has the minimum value with argmin() 
#-> returns index position of targt tensor where the minimum value occurs 
x.argmin()

tensor(0)

In [53]:
x[0]

tensor(1)

In [54]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(19)

In [55]:
x[8]

tensor(81)

##Reshaping 
reshapes an input tensor to a defined shape

##Stacking
 Return a view of an input tensor of certain shape but keep the same memory as the original tensor
##Squeezing 
removes all 1 dimensions from a tensor
##Unsqueezing tensors
add a 1 dimension to a target tensor

**Viewing:** Return a view of an input tensor of certain shape but keep the same memory as the original tensor

**Permute:** Return a view of the input with dimensions permuted (swapped) in a certain way

In [56]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [57]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

#1*9 = 9 < 10 which is the tensor size so compatible 

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [58]:
# Change the view 
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [59]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [60]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [61]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [62]:

# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [63]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}") 
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [64]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]


(tensor(728218.), tensor(728218.))

##Indexing (selecting data from tensors)

In [65]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape



(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [66]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [67]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [68]:
# Let's index on the most inner bracket (last dimension)
x[0][1][1]

tensor(5)

In [69]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [70]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [71]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [72]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [73]:
# Index on x to return 9
print(x[0][2][2])

# Index on x to return 3, 6, 9
print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


###PyTorch tensors & NumPy
-- Data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray)

-- PyTorch tensor -> NumPy -> torch.Tensor.numpy()

In [74]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [75]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [76]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [77]:
# Change the tesnor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

##Reproducbility (trying to take random out of random)
start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...

To reduce the randomness in neural networks and PyTorch comes the concept of a random seed.

Essentially what the random seed does is "flavour" the randomness.

In [78]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4597, 0.3697, 0.9419, 0.8656],
        [0.0468, 0.8863, 0.0656, 0.9064],
        [0.8046, 0.5058, 0.4827, 0.1722]])
tensor([[0.5672, 0.2480, 0.9363, 0.0569],
        [0.2266, 0.4365, 0.1297, 0.2528],
        [0.3795, 0.5812, 0.4863, 0.9423]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [79]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


###Running tensors and PyTorch objects on the GPUs 

In [80]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

False

In [81]:
# Setup device agnostic code 
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [82]:

# Count number of devices
torch.cuda.device_count()

0

In [83]:
!nvidia-smi


NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

