##Importing libraries

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu113


###Creating tensors

In [2]:
#Pytorch tensors are created using torch.Tensor()
scalar = torch.tensor(7)
scalar
#scalar.ndim

tensor(7)

In [3]:
#Getting tensor back as Puthon int 
scalar.item()

7

In [4]:
#Vectors
vector = torch.tensor([8,8])
vector

tensor([8, 8])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
#Matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
MATRIX[1]

tensor([ 9, 10])

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [11]:
TENSOR.ndim

3

In [12]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

##Random Tensors

In [14]:
# Create a random tensor of size (5, 6)
random_tensor = torch.rand(5, 6)
random_tensor

tensor([[0.7441, 0.6595, 0.5837, 0.8375, 0.5063, 0.8833],
        [0.7827, 0.1551, 0.2656, 0.6461, 0.5696, 0.7861],
        [0.2515, 0.7688, 0.1062, 0.0048, 0.1808, 0.1903],
        [0.6876, 0.8643, 0.0607, 0.9016, 0.8773, 0.2152],
        [0.9888, 0.7545, 0.3640, 0.1058, 0.6614, 0.9656]])

In [15]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(4, 224, 224)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([4, 224, 224]), 3)

Zeores and Ones


In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros