##Importing libraries

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu113


###Creating tensors

In [2]:
#Pytorch tensors are created using torch.Tensor()
scalar = torch.tensor(7)
scalar
#scalar.ndim

tensor(7)

In [3]:
#Getting tensor back as Puthon int 
scalar.item()

7

In [4]:
#Vectors
vector = torch.tensor([8,8])
vector

tensor([8, 8])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
#Matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
MATRIX[1]

tensor([ 9, 10])

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [11]:
TENSOR.ndim

3

In [12]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])